name: Full-Stack CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Backend Image
        run: |
          docker build -t your-dockerhub-username/music-app-backend ./backend
          docker push your-dockerhub-username/music-app-backend
          
      - name: Build and Push Frontend Image
        run: |
          docker build -t your-dockerhub-username/music-app-frontend ./frontend
          docker push your-dockerhub-username/music-app-frontend

      - name: Build and Push Admin Portal Image
        run: |
          docker build -t your-dockerhub-username/music-app-admin ./admin-portal
          docker push your-dockerhub-username/music-app-admin

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # FIX: Add a checkout step in the deploy job to get the docker-compose.yml file.
      - name: Checkout Code on Server
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on your server
            cd /home/ubuntu/music-app-fullstack

            # Pull the latest images from Docker Hub
            sudo docker compose pull

            # Rebuild and restart the containers in the background. 
            # The --build is redundant since we are pulling new images, but safe.
            sudo docker compose up -d